# Generated by Django 5.2.3 on 2025-08-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('public_key', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('hashed_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_of_arrival', models.DateTimeField()),
                ('encrypted_subject', models.TextField()),
                ('encrypted_body', models.TextField()),
                ('synced', models.BooleanField(default=False)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to='quantserver.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrote', to='quantserver.users')),
            ],
        ),
    ]
